### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by AdriVanHoudt** [zaggino/brackets-npm-registry#35]
When trying to update registry or even the eslint package I get:

```bash
ERROR: "ReferenceError: Promise is not defined
at .../Library/Application Support/Brackets/extensions/user/brackets-npm-registry/dist/node/node-ensure.js:84:14
at tryCatcher (.../Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/util.js:26:23)
at Promise._settlePromiseFromHandler (.../Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:507:31)
at Promise._settlePromiseAt (.../Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:581:18)
at Promise._settlePromises (.../Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:697:14)
at Async._drainQueue (.../Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:123:16)
at Async._drainQueues (.../Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:133:10)
at Async.drainQueues (.../Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:15:14)
at process._tickCallback (node.js:415:13)"
```

**Comment by zaggino** [comment]
Try deleting the registry and installing again, there's no `Promise` in `node-ensure.js` file.
https://github.com/zaggino/brackets-npm-registry/blob/master/src/node/node-ensure.js

**Comment by AdriVanHoudt** [comment]
ok that fixed it :+1:
