### ISSUE TITLE
SSL error on plugin install using brackets-npm-registry

### ISSUE THREAD

**Issue by clouchtibat** [zaggino/brackets-npm-registry#36]
I have a SSL error when I try to install a plugin using brackets-npm-registry:

npm
 WARN retry
 will retry, error on last attempt: Error: tunneling socket could not be established, cause=140526336669568:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:766:

npm WARN
 retry 

npm ERR! 
fetch failed https://registry.npmjs.org/brackets-eslint/-/brackets-eslint-2.1.3.tgz

{ cause: 
   { [Error: tunneling socket could not be established, cause=140526336669568:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:766:
   ] code: 'ECONNRESET' },
  isOperational: true,
  code: 'ECONNRESET' }

Unhandled rejection Error: tunneling socket could not be established, cause=140526336669568:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:766:

    at ClientRequest.onError (/home/dev/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:174:17)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1547:9)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at SecurePair.<anonymous> (tls.js:1400:15)
    at SecurePair.EventEmitter.emit (events.js:95:17)
    at SecurePair.error (tls.js:1020:27)
    at CleartextStream.read [as _read] (tls.js:460:17)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)

I manage to directly download the archive at https://registry.npmjs.org/brackets-eslint/-/brackets-eslint-2.1.3.tgz so it's certainly a network configuration issue, do you have any suggestion about that?

**Comment by zaggino** [comment]
not really, never seen anything like that before

**Comment by clouchtibat** [comment]
I finally managed to install the plugin by changing my network configuration. Sorry for the trouble.
